### ISSUE TITLE
Automated Documentation Deployment via GitHub Actions

### ISSUE THREAD

**Issue by esatemre** [ProdFact/telamentis#1]
### Summary

**As a** developer,
**I want** our documentation to be automatically built and deployed using MkDocs via GitHub Actions
**so that** it is always up-to-date and publicly accessible through GitHub Pages.

---

### 🎯 Goals / Acceptance Criteria

* [ ] A GitHub Actions workflow file exists at `.github/workflows/deploy.yml`.
* [ ] The workflow runs **on push to the `main` branch**.
* [ ] The workflow sets up Python (e.g., version 3.11) and installs `mkdocs` and any necessary plugins.
* [ ] The documentation is built using `mkdocs build` or `mkdocs gh-deploy`.
* [ ] The output is deployed to the `gh-pages` branch using `mkdocs gh-deploy --force`.
* [ ] The GitHub Pages site is live at the expected URL (based on repo settings).
* [ ] If we’re using a custom domain, the workflow includes support for retaining the `CNAME` file.
* [ ] The workflow uses GitHub’s built-in `GITHUB_TOKEN` (no manual secrets required).

---

### 🛠️ Technical Notes

* Ensure `mkdocs.yml` exists at the root and is correctly configured.
* Ensure a `/docs` directory exists with at least an `index.md` file.
* Use the `mkdocs-material` theme unless otherwise specified.
* To verify locally:

  ```bash
  pip install mkdocs mkdocs-material
  mkdocs serve
  ```

---

### 📌 Example Workflow Snippet

```yaml
name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
```

---

### ✅ Definition of Done

* MkDocs site is automatically deployed on every push to `main`.
* GitHub Pages shows the latest documentation.
* No manual steps are required after merging PRs that update documentation.
